// prod.js --> Production keys here!!
// In order for it to work properly after deploying, first make sure
//  you set up the environment variables correctly ;)

module.exports = {

  // https://developers.google.com
  googleClientID: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,

  // https://www.mongodb.com/
  mongoURI: process.env.MONGO_URI,

  // Random set of strings generated by your fingers :)
  cookieKey: process.env.COOKIE_KEY,

  // https://stripe.com/
  stripePublishableKey: process.env.STRIPE_PUBLISHABLE_KEY,
  stripeSecretKey: process.env.STRIPE_SECRET_KEY,

  // https://sendgrid.com/
  sendGridKey: process.env.SEND_GRID_KEY,

  // Your current ROOT domain - Prod  Vs Dev
  redirectDomain: process.env.REDIRECT_DOMAIN
};
